from  web_fetch_def import fetch_fnc

fetch_fnc("https://duckduckgo.com/html/?q=stock+vfiax&ia=web",{"result__url","result__snippet","result__title"})
fetch_fnc("https://duckduckgo.com/html/?q=stock+vig&ia=web",{"result__url","result__snippet","result__title"})
fetch_fnc("https://duckduckgo.com/html/?q=stock+rxdx&ia=web",{"result__url","result__snippet","result__title"})
fetch_fnc("https://duckduckgo.com/html/?q=gilead+gild&ia=web",{"result__url","result__snippet","result__title"})
fetch_fnc("https://duckduckgo.com/html/?q=cldx&ia=web",{"result__url","result__snippet","result__title"})
fetch_fnc("https://duckduckgo.com/html/?q=stock+ardo&ia=web",{"result__url","result__snippet","result__title"})
fetch_fnc("https://duckduckgo.com/html/?q=unitedhealth+UNH&ia=web",{"result__url","result__snippet","result__title"})
fetch_fnc("https://duckduckgo.com/html/?q=biotech&ia=web",{"result__url","result__snippet","result__title"})
fetch_fnc("https://duckduckgo.com/html/?q=broadcom+BRCM&ia=web",{"result__url","result__snippet","result__title"})
fetch_fnc("https://duckduckgo.com/html/?q=optum&ia=web",{"result__url","result__snippet","result__title"})
from  web_fetch_def import fetch_fnc
fetch_fnc("https://duckduckgo.com/html/?q=cdisc&ia=web",{"result__url","result__snippet","result__title"})
fetch_fnc("https://duckduckgo.com/html/?q=dmhc+encounter&ia=web",{"result__url","result__snippet","result__title"})
fetch_fnc("https://duckduckgo.com/html/?q=cms+encounter&ia=web",{"result__url","result__snippet","result__title"})
fetch_fnc("https://duckduckgo.com/html/?q=hedis&ia=web",{"result__url","result__snippet","result__title"})
fetch_fnc("https://duckduckgo.com/html/?q=ncqa&ia=web",{"result__url","result__snippet","result__title"})
fetch_fnc("https://duckduckgo.com/html/?q=fda&ia=web",{"result__url","result__snippet","result__title"})
fetch_fnc("https://duckduckgo.com/html/?q=trans+union+edi+clearing+house&ia=web",{"result__url","result__snippet","result__title"})
from  web_fetch_def import fetch_fnc
fetch_fnc("https://duckduckgo.com/html/?q=payer+edi+clearing+house&ia=web",{"result__url","result__snippet","result__title"})
fetch_fnc("https://duckduckgo.com/html/?q=837+x12&ia=web",{"result__url","result__snippet","result__title"})
fetch_fnc("https://duckduckgo.com/html/?q=ub92&ia=web",{"result__url","result__snippet","result__title"})
fetch_fnc("https://duckduckgo.com/html/?q=nppes+npi&ia=web",{"result__url","result__snippet","result__title"})
fetch_fnc("https://duckduckgo.com/html/?q=mpin+member+id+contract&ia=web",{"result__url","result__snippet","result__title"})
fetch_fnc("https://duckduckgo.com/html/?q=delegated+provider&ia=web",{"result__url","result__snippet","result__title"})
from  web_fetch_def import fetch_fnc
fetch_fnc("https://duckduckgo.com/html/?q=provider+network+healthcare&ia=web",{"result__url","result__snippet","result__title"})
fetch_fnc("https://duckduckgo.com/html/?q=emdeon+payer+list&ia=web",{"result__url","result__snippet","result__title"})
fetch_fnc("https://duckduckgo.com/html/?q=healthcare+provider+contract&ia=web",{"result__url","result__snippet","result__title"})
fetch_fnc("https://duckduckgo.com/html/?q=DRG+Diagnostic+Related+Groups&ia=web",{"result__url","result__snippet","result__title"})
fetch_fnc("https://duckduckgo.com/html/?q=EOB+Explanation+of+Benefits&ia=web",{"result__url","result__snippet","result__title"})
fetch_fnc("https://duckduckgo.com/html/?q=EOMB+Explanation+of+Medicare+Benefits&ia=web",{"result__url","result__snippet","result__title"})
from  web_fetch_def import fetch_fnc
fetch_fnc("https://duckduckgo.com/html/?q=EPD+Expanded+Provider+Database&ia=web",{"result__url","result__snippet","result__title"})
fetch_fnc("https://duckduckgo.com/html/?q=HCFA+Common+Procedural+Coding+System+HCPCS&ia=web",{"result__url","result__snippet","result__title"})
fetch_fnc("https://duckduckgo.com/html/?q=Health+Plan+Employer+Data+Information+Set+hedis&ia=web",{"result__url","result__snippet","result__title"})
fetch_fnc("https://duckduckgo.com/html/?q=HIPAA+Health+Insurance+Portability+Accountability+Act&ia=web",{"result__url","result__snippet","result__title"})
fetch_fnc("https://duckduckgo.com/html/?q=International+Classification+Diseases+ICD-9&ia=web",{"result__url","result__snippet","result__title"})
from  web_fetch_def import fetch_fnc
fetch_fnc("https://duckduckgo.com/html/?q=International+Classification+Diseases+ICD-10&ia=web",{"result__url","result__snippet","result__title"})
fetch_fnc("https://duckduckgo.com/html/?q=NCQR+National+Claim+Quality+Review&ia=web",{"result__url","result__snippet","result__title"})
fetch_fnc("https://duckduckgo.com/html/?q=NDB+Network+Database&ia=web",{"result__url","result__snippet","result__title"})
fetch_fnc("https://duckduckgo.com/html/?q=UR+Utilization+Review&ia=web",{"result__url","result__snippet","result__title"})
from  web_fetch_def import fetch_fnc
fetch_fnc("https://duckduckgo.com/html/?q=WebMD&ia=web",{"result__url","result__snippet","result__title"})
fetch_fnc("http://www.businessopportunity.com/",{"ListingCopy","ListingDesc","result__title"})
fetch_fnc("http://www.franchiseclique.com/industry/business-opportunities",{"col-xs-12 col-sm-3","minCashRequired","pricing-content"})
