from  web_fetch_def import fetch_fnc
fetch_fnc("https://duckduckgo.com/html/?q=news",{"result__url","result__snippet","result__title"})
fetch_fnc("https://duckduckgo.com/html/?q=unitedhealth",{"result__url","result__snippet","result__title"})
fetch_fnc("https://duckduckgo.com/html/?q=biotech",{"result__url","result__snippet","result__title"})
fetch_fnc("http://orangecounty.backpage.com/TherapeuticMassage/",'sponsorBoxContent')
fetch_fnc("https://duckduckgo.com/html/?q=broadcom",{"result__url","result__snippet","result__title"})
fetch_fnc("https://www.classifiedads.com/search.php?keywords=&cid=272&lid=gx16596&lname=Orange+County",{"resultitem","result-hood"})
fetch_fnc("https://orangecounty.craigslist.org/search/thp",{"result-title hdrlnk","result-hood"})
fetch_fnc("https://orangecounty.craigslist.org/search/jjj",{"result-info","result-title hdrlnk","result-hood"})
fetch_fnc("https://vietnam.craigslist.org/search/ppp?areaAbb=vietnam",{"result-title","result-title hdrlnk","result-hood"})
fetch_fnc("https://vietnam.craigslist.org/search/bbb?areaAbb=vietnam",{"result-title","result-title hdrlnk","result-hood"})
fetch_fnc("http://www.fvhs.com/",{"item-summary cf","items-list"})
fetch_fnc("http://www.gazettes.com/classifieds/",{"card event-list","tab-content"})
fetch_fnc("http://hot-ads.com/newspaper/index.cfm?SID=NY&RGID=10000000000&Category=8&Classification=801","body_text")
fetch_fnc("https://www.indeed.com/l-Huntington-Beach,-CA-jobs.html",{"jobtitle turnstileLink","sjcl","row  result","company","no-wrap","location"})
fetch_fnc("http://www.kimquy.com/rao-vat/raovat.html?vw=ad_list&cid=99","grid12")
fetch_fnc("http://www.onebackpage.com/",{"handpicked_items clearfix","pull-right","pull-left","container owl-front-page","feat_item","result-hood"})
fetch_fnc("https://duckduckgo.com/html/?q=phuquoc",{"result__url","result__snippet","result__title"})
fetch_fnc("https://duckduckgo.com/html/?q=python",{"result__url","result__snippet","result__title"})
fetch_fnc("https://raovat.net/","rvn-item-title")
fetch_fnc("http://www.raovat365ngay.com/raovat.php","post-body")
fetch_fnc("https://www.rubmaps.com/","theadFloat")
fetch_fnc("https://www.nguoi-viet.com/sinh-hoat-cong-dong/sinh-hoat-cong-dong/","td-post-content")
fetch_fnc("http://www.snagajob.com/jobs/california/huntington_beach_jobs.html",{"section-body","job-title","row  result","company","no-wrap","location"})
fetch_fnc("https://www.surfcityusa.com/events/?month=9&year=2017","item-child")
fetch_fnc("https://duckduckgo.com/html/?q=unitedhealth",{"result__url","result__snippet","result__title"})
fetch_fnc("https://raovat.vietbao.com","nw_boxing_content")

